#ifndef NES_STATE_META_H
#define NES_STATE_META_H

#include "nes/emulator.h"
#include "serialize.h"

typedef enum
{
	NES_RECORD_NONE = 0,
	NES_RECORD_EMULATOR,
	NES_RECORD_CPU,
	NES_RECORD_PPU,
	NES_RECORD_PPU_SPRITE,
	NES_RECORD_APU,
	NES_RECORD_APU_DIVIDER,
	NES_RECORD_APU_SWEEP,
	NES_RECORD_APU_ENVELOPE,
	NES_RECORD_APU_PULSE,
	NES_RECORD_APU_TRIANGLE,
	NES_RECORD_COUNT,
}
NES_RecordId;

// Public field IDs are stable integration keys. Do not reorder or reuse an ID;
// add new fields immediately before COUNT. Consumers can use COUNT to allocate
// a flat table and use NES_StateField.id as its index.
typedef enum
{
	NES_STATE_FIELD_ID_NONE = 0,

	// IDs 1-3 belonged to the removed publication wrapper. Keep the first live
	// field explicit so serialized/debugger integration IDs never shift.
	NES_STATE_FIELD_ID_CPU_A = 4,

	NES_STATE_FIELD_ID_CPU_X,
	NES_STATE_FIELD_ID_CPU_Y,
	NES_STATE_FIELD_ID_CPU_S,
	NES_STATE_FIELD_ID_CPU_P,
	NES_STATE_FIELD_ID_CPU_PC,
	NES_STATE_FIELD_ID_CPU_CYCLES,

	NES_STATE_FIELD_ID_PPU_SPRITE_YPOS,
	NES_STATE_FIELD_ID_PPU_SPRITE_XPOS,
	NES_STATE_FIELD_ID_PPU_SPRITE_INDEX,
	NES_STATE_FIELD_ID_PPU_SPRITE_ATTRS,

	NES_STATE_FIELD_ID_PPU_CYCLES,
	NES_STATE_FIELD_ID_PPU_XTICK,
	NES_STATE_FIELD_ID_PPU_YTICK,
	NES_STATE_FIELD_ID_PPU_T,
	NES_STATE_FIELD_ID_PPU_V,
	NES_STATE_FIELD_ID_PPU_X,
	NES_STATE_FIELD_ID_PPU_W,
	NES_STATE_FIELD_ID_PPU_TILE_ID,
	NES_STATE_FIELD_ID_PPU_TILE_HI,
	NES_STATE_FIELD_ID_PPU_TILE_LO,
	NES_STATE_FIELD_ID_PPU_ATR_B,
	NES_STATE_FIELD_ID_PPU_ATR_L0,
	NES_STATE_FIELD_ID_PPU_ATR_L1,
	NES_STATE_FIELD_ID_PPU_CHR_R0,
	NES_STATE_FIELD_ID_PPU_CHR_R1,
	NES_STATE_FIELD_ID_PPU_ATR_R0,
	NES_STATE_FIELD_ID_PPU_ATR_R1,
	NES_STATE_FIELD_ID_PPU_SPR0_ENABLE,
	NES_STATE_FIELD_ID_PPU_SPR0_2CYCLE_DELAY,
	NES_STATE_FIELD_ID_PPU_NERRORS,
	NES_STATE_FIELD_ID_PPU_PPUADDR,
	NES_STATE_FIELD_ID_PPU_PPUCTRL,
	NES_STATE_FIELD_ID_PPU_PPUDATA,
	NES_STATE_FIELD_ID_PPU_OAMDMA,
	NES_STATE_FIELD_ID_PPU_PPUMASK,
	NES_STATE_FIELD_ID_PPU_PPUSTATUS,
	NES_STATE_FIELD_ID_PPU_OAMADDR,
	NES_STATE_FIELD_ID_PPU_OAMDATA,
	NES_STATE_FIELD_ID_PPU_DATA_READ_BUF,
	NES_STATE_FIELD_ID_PPU_DATA_READ_ADR,
	NES_STATE_FIELD_ID_PPU_NSPRS,
	NES_STATE_FIELD_ID_PPU_SPRS,
	NES_STATE_FIELD_ID_PPU_OAM,
	NES_STATE_FIELD_ID_PPU_PRAM,

	NES_STATE_FIELD_ID_APU_DIVIDER_COUNTER,
	NES_STATE_FIELD_ID_APU_DIVIDER_PERIOD,

	NES_STATE_FIELD_ID_APU_SWEEP_DIVIDER,
	NES_STATE_FIELD_ID_APU_SWEEP_RELOAD_DIVIDER,
	NES_STATE_FIELD_ID_APU_SWEEP_SHIFT,
	NES_STATE_FIELD_ID_APU_SWEEP_ENABLE,
	NES_STATE_FIELD_ID_APU_SWEEP_NEGATE,

	NES_STATE_FIELD_ID_APU_ENVELOPE_DIVIDER,
	NES_STATE_FIELD_ID_APU_ENVELOPE_COUNTER,
	NES_STATE_FIELD_ID_APU_ENVELOPE_RELOAD_DIVIDER,

	NES_STATE_FIELD_ID_APU_PULSE_ENABLE,
	NES_STATE_FIELD_ID_APU_PULSE_INFINITE_PLAY,
	NES_STATE_FIELD_ID_APU_PULSE_DURATION,
	NES_STATE_FIELD_ID_APU_PULSE_VOLUME,
	NES_STATE_FIELD_ID_APU_PULSE_USE_CONSTANT_VOLUME,
	NES_STATE_FIELD_ID_APU_PULSE_SWEEP,
	NES_STATE_FIELD_ID_APU_PULSE_ENV,
	NES_STATE_FIELD_ID_APU_PULSE_DUTY_MASK,
	NES_STATE_FIELD_ID_APU_PULSE_PHASE,
	NES_STATE_FIELD_ID_APU_PULSE_TIMER,
	NES_STATE_FIELD_ID_APU_PULSE_TIMER_PERIOD,

	NES_STATE_FIELD_ID_APU_IRQ_PENDING,
	NES_STATE_FIELD_ID_APU_IRQ_INHIBIT,
	NES_STATE_FIELD_ID_APU_RESET_DELAY,
	NES_STATE_FIELD_ID_APU_RESET_MODE,
	NES_STATE_FIELD_ID_APU_MODE,
	NES_STATE_FIELD_ID_APU_STEP_INDEX,
	NES_STATE_FIELD_ID_APU_CPU_CYCLE_COUNTER,
	NES_STATE_FIELD_ID_APU_PULSE,

	NES_STATE_FIELD_ID_EMULATOR_MAPPER_NUMBER,
	NES_STATE_FIELD_ID_EMULATOR_NUM_CHR_BANKS,
	NES_STATE_FIELD_ID_EMULATOR_NUM_PRG_BANKS,
	NES_STATE_FIELD_ID_EMULATOR_PRG_ROM_SIZE,
	NES_STATE_FIELD_ID_EMULATOR_CHR_ROM_SIZE,
	NES_STATE_FIELD_ID_EMULATOR_PRG_BANK_SIZE,
	NES_STATE_FIELD_ID_EMULATOR_CHR_BANK_SIZE,
	NES_STATE_FIELD_ID_EMULATOR_VMIRROR,
	NES_STATE_FIELD_ID_EMULATOR_VALUES,
	NES_STATE_FIELD_ID_EMULATOR_INPUT_STATE,
	NES_STATE_FIELD_ID_EMULATOR_MASTER_CLOCK,
	NES_STATE_FIELD_ID_EMULATOR_CPU,
	NES_STATE_FIELD_ID_EMULATOR_PPU,
	NES_STATE_FIELD_ID_EMULATOR_CONTROLLERS,
	NES_STATE_FIELD_ID_EMULATOR_WRAM,
	NES_STATE_FIELD_ID_EMULATOR_VRAM,
	NES_STATE_FIELD_ID_EMULATOR_CHR_ROM,
	NES_STATE_FIELD_ID_EMULATOR_PRG_ROM,
	NES_STATE_FIELD_ID_EMULATOR_CHR_RAM,
	NES_STATE_FIELD_ID_EMULATOR_PRG_RAM,
	NES_STATE_FIELD_ID_EMULATOR_APU,
	NES_STATE_FIELD_ID_EMULATOR_VIDEO,
	// Reserved so later public field IDs remain stable.
	NES_STATE_FIELD_ID_EMULATOR_AUDIO_SAMPLE_PHASE,
	NES_STATE_FIELD_ID_EMULATOR_CPU_STALL_CYCLES,

	NES_STATE_FIELD_ID_APU_TRIANGLE_ENABLE,
	NES_STATE_FIELD_ID_APU_TRIANGLE_LENGTH_COUNTER,
	NES_STATE_FIELD_ID_APU_TRIANGLE_LENGTH_COUNTER_HALT,
	NES_STATE_FIELD_ID_APU_TRIANGLE_LINEAR_COUNTER,
	NES_STATE_FIELD_ID_APU_TRIANGLE_LINEAR_COUNTER_RELOAD,
	NES_STATE_FIELD_ID_APU_TRIANGLE_LINEAR_COUNTER_RELOAD_VALUE,
	NES_STATE_FIELD_ID_APU_TRIANGLE_WAVE_PHASE,
	NES_STATE_FIELD_ID_APU_TRIANGLE_WAVE_PERIOD,
	NES_STATE_FIELD_ID_APU_TRIANGLE_WAVE_TIMER,
	NES_STATE_FIELD_ID_APU_TRIANGLE,
	NES_STATE_FIELD_ID_EMULATOR_SAMPLE_PHASE,

	NES_STATE_FIELD_ID_COUNT,
}
NES_StateFieldID;

typedef enum
{
	NES_STATE_FIELD_SERIALIZED       = SERIALIZE_FIELD_ENABLED,
	NES_STATE_FIELD_DEBUG_VISIBLE    = 1 << 2,
}
NES_StateFieldFlags;

typedef SerializeField NES_StateField;
typedef SerializeRecord NES_StateRecord;

const SerializeRecordMap *nes_state_record_map(void);
const NES_StateRecord *nes_state_record(NES_RecordId record_id);
const NES_StateField *nes_state_field_from_id(NES_StateFieldID id);
const NES_StateField *nes_state_visible_field(const NES_StateRecord *record, u32 visible_index);
u32 nes_state_visible_field_count(const NES_StateRecord *record);

#endif
