#include "nes/state_meta.h"
#include "emulator_internal.h"
#define STATE_FIELD(id_, type_, field_, wire_type_, record_id_, count_, flags_) \
	{ \
		.name = #field_, \
		.id = (id_), \
		.wire_type = (wire_type_), \
		.record_id = (record_id_), \
		.offset = offsetof(type_, field_), \
		.size = sizeof(((type_ *)0)->field_), \
		.count = (count_), \
		.flags = (flags_), \
	}

#define SERIAL_FIELD(id_, type_, field_, wire_type_, record_id_) \
	STATE_FIELD(id_, type_, field_, wire_type_, record_id_, 1, NES_STATE_FIELD_SERIALIZED)

#define SERIAL_ARRAY_FIELD(id_, type_, field_, wire_type_, record_id_) \
	STATE_FIELD(id_, type_, field_, wire_type_, record_id_, ArrayCount(((type_ *)0)->field_), \
		NES_STATE_FIELD_SERIALIZED)

#define DEBUG_SERIAL_FIELD(id_, type_, field_, wire_type_, record_id_) \
	STATE_FIELD(id_, type_, field_, wire_type_, record_id_, 1, \
		NES_STATE_FIELD_SERIALIZED | NES_STATE_FIELD_DEBUG_VISIBLE)

static const NES_StateField nes_cpu_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_CPU_A, NES_CPUState, A, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_CPU_X, NES_CPUState, X, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_CPU_Y, NES_CPUState, Y, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_CPU_S, NES_CPUState, S, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_CPU_P, NES_CPUState, P, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_CPU_PC, NES_CPUState, PC, SERIALIZE_WIRE_U16, 0),
};

static const NES_StateField nes_ppu_sprite_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_SPRITE_YPOS, NES_PPUSprite, ypos, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_SPRITE_XPOS, NES_PPUSprite, xpos, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_SPRITE_INDEX, NES_PPUSprite, index, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_SPRITE_ATTRS, NES_PPUSprite, attrs, SERIALIZE_WIRE_U8, 0),
};

static const NES_StateField nes_ppu_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_XTICK, NES_PPUState, xtick, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_YTICK, NES_PPUState, ytick, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_T, NES_PPUState, t, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_V, NES_PPUState, v, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_X, NES_PPUState, x, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_W, NES_PPUState, w, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_TILE_ID, NES_PPUState, tile_id, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_TILE_HI, NES_PPUState, tile_hi, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_TILE_LO, NES_PPUState, tile_lo, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_ATR_B, NES_PPUState, atr_b, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_ATR_L0, NES_PPUState, atr_l0, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_ATR_L1, NES_PPUState, atr_l1, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_CHR_R0, NES_PPUState, chr_r0, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_CHR_R1, NES_PPUState, chr_r1, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_ATR_R0, NES_PPUState, atr_r0, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_ATR_R1, NES_PPUState, atr_r1, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_SPR0_ENABLE, NES_PPUState, spr0_enable, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_SPR0_2CYCLE_DELAY, NES_PPUState, spr0_2cycle_delay, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_PPUCTRL, NES_PPUState, PPUCTRL, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_PPUMASK, NES_PPUState, PPUMASK, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_PPUSTATUS, NES_PPUState, PPUSTATUS, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_OAMADDR, NES_PPUState, OAMADDR, SERIALIZE_WIRE_U8, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_DATA_READ_BUF, NES_PPUState, data_read_buf, SERIALIZE_WIRE_U8, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_PPU_NSPRS, NES_PPUState, nsprs, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_PPU_SPRS, NES_PPUState, sprs, SERIALIZE_WIRE_RECORD, NES_RECORD_PPU_SPRITE),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_PPU_OAM, NES_PPUState, OAM, SERIALIZE_WIRE_RECORD, NES_RECORD_PPU_SPRITE),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_PPU_PRAM, NES_PPUState, _pram, SERIALIZE_WIRE_U8, 0),
};

static const NES_StateField nes_apu_divider_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_DIVIDER_COUNTER, NES_APUDivider, counter, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_DIVIDER_PERIOD, NES_APUDivider, period, SERIALIZE_WIRE_U8, 0),
};

static const NES_StateField nes_apu_sweep_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_SWEEP_DIVIDER, NES_APUSweep, divider, SERIALIZE_WIRE_RECORD, NES_RECORD_APU_DIVIDER),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_SWEEP_RELOAD_DIVIDER, NES_APUSweep, reload_divider, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_SWEEP_SHIFT, NES_APUSweep, shift, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_SWEEP_ENABLE, NES_APUSweep, enable, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_SWEEP_NEGATE, NES_APUSweep, negate, SERIALIZE_WIRE_U8, 0),
};

static const NES_StateField nes_apu_envelope_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_ENVELOPE_DIVIDER, NES_APUEnvelope, divider, SERIALIZE_WIRE_RECORD, NES_RECORD_APU_DIVIDER),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_ENVELOPE_COUNTER, NES_APUEnvelope, counter, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_ENVELOPE_RELOAD_DIVIDER, NES_APUEnvelope, reload_divider, SERIALIZE_WIRE_U8, 0),
};

static const NES_StateField nes_apu_pulse_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_ENABLE, NES_APU_Pulse, enable, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_INFINITE_PLAY, NES_APU_Pulse, infinite_play, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_DURATION, NES_APU_Pulse, length_counter, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_VOLUME, NES_APU_Pulse, volume, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_USE_CONSTANT_VOLUME, NES_APU_Pulse, use_constant_volume, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_SWEEP, NES_APU_Pulse, sweep, SERIALIZE_WIRE_RECORD, NES_RECORD_APU_SWEEP),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_ENV, NES_APU_Pulse, env, SERIALIZE_WIRE_RECORD, NES_RECORD_APU_ENVELOPE),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_DUTY_MASK, NES_APU_Pulse, duty_mask, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_PHASE, NES_APU_Pulse, phase, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_TIMER, NES_APU_Pulse, timer, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_PULSE_TIMER_PERIOD, NES_APU_Pulse, timer_period, SERIALIZE_WIRE_U16, 0),
};

static const NES_StateField nes_apu_triangle_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_ENABLE, NES_APU_Triangle, enable, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_LENGTH_COUNTER, NES_APU_Triangle, length_counter, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_LENGTH_COUNTER_HALT, NES_APU_Triangle, length_counter_halt, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_LINEAR_COUNTER, NES_APU_Triangle, linear_counter, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_LINEAR_COUNTER_RELOAD, NES_APU_Triangle, linear_counter_reload, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_LINEAR_COUNTER_RELOAD_VALUE, NES_APU_Triangle, linear_counter_reload_value, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_WAVE_PHASE, NES_APU_Triangle, wave_phase, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_WAVE_PERIOD, NES_APU_Triangle, wave_period, SERIALIZE_WIRE_U16, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE_WAVE_TIMER, NES_APU_Triangle, wave_timer, SERIALIZE_WIRE_U16, 0),
};

static const NES_StateField nes_apu_fields[] =
{
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_IRQ_PENDING, NES_APUState, irq_pending, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_IRQ_INHIBIT, NES_APUState, irq_inhibit, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_RESET_DELAY, NES_APUState, reset_delay, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_RESET_MODE, NES_APUState, reset_mode, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_MODE, NES_APUState, mode, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_STEP_INDEX, NES_APUState, step_index, SERIALIZE_WIRE_U8, 0),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_CPU_CYCLE_COUNTER, NES_APUState, cpu_cycle_counter, SERIALIZE_WIRE_U16, 0),
	STATE_FIELD(NES_STATE_FIELD_ID_APU_PULSE, NES_APUState, pulse, SERIALIZE_WIRE_RECORD, NES_RECORD_APU_PULSE,
		ArrayCount(((NES_APUState *)0)->pulse),
		NES_STATE_FIELD_SERIALIZED | NES_STATE_FIELD_DEBUG_VISIBLE),
	DEBUG_SERIAL_FIELD(NES_STATE_FIELD_ID_APU_TRIANGLE, NES_APUState, triangle, SERIALIZE_WIRE_RECORD, NES_RECORD_APU_TRIANGLE),
};

static const NES_StateField nes_machine_fields[] =
{
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_MAPPER_NUMBER, NES_State, mapper, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_NUM_CHR_BANKS, NES_State, num_chr_banks, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_NUM_PRG_BANKS, NES_State, num_prg_banks, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_PRG_ROM_SIZE, NES_State, prg_rom_size, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_CHR_ROM_SIZE, NES_State, chr_rom_size, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_PRG_BANK_SIZE, NES_State, prg_bank_size, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_CHR_BANK_SIZE, NES_State, chr_bank_size, SERIALIZE_WIRE_U32, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_VMIRROR, NES_State, vmirror, SERIALIZE_WIRE_I32, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_VALUES, NES_State, values, SERIALIZE_WIRE_U8, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_INPUT_STATE, NES_State, input_state, SERIALIZE_WIRE_BYTES, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_CPU_STALL_CYCLES, NES_State, cpu_stall_cycles, SERIALIZE_WIRE_U32, 0),
	STATE_FIELD(NES_STATE_FIELD_ID_MACHINE_CPU, NES_State, cpu, SERIALIZE_WIRE_RECORD, NES_RECORD_CPU, 1,
		NES_STATE_FIELD_SERIALIZED),
	STATE_FIELD(NES_STATE_FIELD_ID_MACHINE_PPU, NES_State, ppu, SERIALIZE_WIRE_RECORD, NES_RECORD_PPU, 1,
		NES_STATE_FIELD_SERIALIZED),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_CONTROLLERS, NES_State, controllers, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_WRAM, NES_State, _wram, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_VRAM, NES_State, _vram, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_CHR_ROM, NES_State, chr_rom, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_PRG_ROM, NES_State, prg_rom, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_CHR_RAM, NES_State, chr_ram, SERIALIZE_WIRE_U8, 0),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_MACHINE_PRG_RAM, NES_State, prg_ram, SERIALIZE_WIRE_U8, 0),
	SERIAL_FIELD(NES_STATE_FIELD_ID_MACHINE_APU, NES_State, apu, SERIALIZE_WIRE_RECORD, NES_RECORD_APU),
};

static const NES_StateField nes_emulator_fields[] =
{
	STATE_FIELD(NES_STATE_FIELD_ID_EMULATOR_MACHINE, NES_Emulator, core, SERIALIZE_WIRE_RECORD, NES_RECORD_MACHINE, 1,
		NES_STATE_FIELD_SERIALIZED),
	SERIAL_ARRAY_FIELD(NES_STATE_FIELD_ID_EMULATOR_VIDEO, NES_Emulator, video, SERIALIZE_WIRE_U8, 0),
};

#define STATE_RECORD(id_, c_type_, fields_) \
	[id_] = { \
		.name = #c_type_, \
		.id = (id_), \
		.size = sizeof(c_type_), \
		.fields = (fields_), \
		.field_count = ArrayCount(fields_), \
	}

static const NES_StateRecord nes_state_records[NES_RECORD_COUNT] =
{
	STATE_RECORD(NES_RECORD_MACHINE, NES_State, nes_machine_fields),
	STATE_RECORD(NES_RECORD_CPU, NES_CPUState, nes_cpu_fields),
	STATE_RECORD(NES_RECORD_PPU, NES_PPUState, nes_ppu_fields),
	STATE_RECORD(NES_RECORD_PPU_SPRITE, NES_PPUSprite, nes_ppu_sprite_fields),
	STATE_RECORD(NES_RECORD_APU, NES_APUState, nes_apu_fields),
	STATE_RECORD(NES_RECORD_APU_DIVIDER, NES_APUDivider, nes_apu_divider_fields),
	STATE_RECORD(NES_RECORD_APU_SWEEP, NES_APUSweep, nes_apu_sweep_fields),
	STATE_RECORD(NES_RECORD_APU_ENVELOPE, NES_APUEnvelope, nes_apu_envelope_fields),
	STATE_RECORD(NES_RECORD_APU_PULSE, NES_APU_Pulse, nes_apu_pulse_fields),
	STATE_RECORD(NES_RECORD_EMULATOR, NES_Emulator, nes_emulator_fields),
	STATE_RECORD(NES_RECORD_APU_TRIANGLE, NES_APU_Triangle, nes_apu_triangle_fields),
};

static const SerializeRecordMap nes_records =
{
	.records = nes_state_records,
	.record_count = ArrayCount(nes_state_records),
};

const SerializeRecordMap *nes_state_record_map(void)
{
	return &nes_records;
}

const NES_StateRecord *nes_state_record(NES_RecordId record_id)
{
	return serialize_record_from_id(&nes_records, (u16)record_id);
}

const NES_StateField *nes_state_field_from_id(NES_StateFieldID id)
{
	if (id <= NES_STATE_FIELD_ID_NONE || id >= NES_STATE_FIELD_ID_COUNT)
	{
		return 0;
	}

	for (u32 type = 0; type < ArrayCount(nes_state_records); ++type)
	{
		const NES_StateRecord *record = &nes_state_records[type];
		for (u32 field_index = 0; field_index < record->field_count; ++field_index)
		{
			const NES_StateField *field = &record->fields[field_index];
			if (field->id == id) return field;
		}
	}
	return 0;
}

u32 nes_state_visible_field_count(const NES_StateRecord *record)
{
	Assert(record);
	u32 count = 0;
	for (u32 index = 0; index < record->field_count; ++index)
	{
		count += !!(record->fields[index].flags & NES_STATE_FIELD_DEBUG_VISIBLE);
	}
	return count;
}

const NES_StateField *nes_state_visible_field(
	const NES_StateRecord *record, u32 visible_index)
{
	Assert(record);
	for (u32 index = 0; index < record->field_count; ++index)
	{
		const NES_StateField *field = &record->fields[index];
		if (!(field->flags & NES_STATE_FIELD_DEBUG_VISIBLE)) continue;
		if (visible_index == 0) return field;
		--visible_index;
	}
	return 0;
}
