#include "nes_serialize.h"
#include "serialize.h"
#include <stdlib.h>

enum
{
	ORB_NES_STATE_MAX_ENCODED_SIZE = KiB(256),
};

typedef enum
{
	// These values are part of the STAT wire format. Append new IDs and bump
	// ORB_STATE_VERSION before making an incompatible schema change.
	ORB_NES_RECORD_NONE = 0,
	ORB_NES_RECORD_STATE,
	ORB_NES_RECORD_CPU,
	ORB_NES_RECORD_PPU,
	ORB_NES_RECORD_PPU_SPRITE,
	ORB_NES_RECORD_APU,
	ORB_NES_RECORD_APU_DIVIDER,
	ORB_NES_RECORD_APU_SWEEP,
	ORB_NES_RECORD_APU_ENVELOPE,
	ORB_NES_RECORD_APU_PULSE,
	ORB_NES_RECORD_APU_TRIANGLE,
	ORB_NES_RECORD_COUNT,
}
Orb_NESRecordId;

typedef enum
{
	// Field IDs are also persisted in STAT. Keep existing values stable.
	ORB_NES_FIELD_NONE = 0,

	ORB_NES_FIELD_STATE_SCHEDULER_CLOCK,
	ORB_NES_FIELD_STATE_SAMPLE_PHASE,
	ORB_NES_FIELD_STATE_VALUES,
	ORB_NES_FIELD_STATE_INPUT,
	ORB_NES_FIELD_STATE_CPU_STALL_CYCLES,
	ORB_NES_FIELD_STATE_CPU,
	ORB_NES_FIELD_STATE_PPU,
	ORB_NES_FIELD_STATE_APU,
	ORB_NES_FIELD_STATE_CONTROLLERS,
	ORB_NES_FIELD_STATE_WRAM,
	ORB_NES_FIELD_STATE_VRAM,
	ORB_NES_FIELD_STATE_CHR_RAM,
	ORB_NES_FIELD_STATE_PRG_RAM,
	ORB_NES_FIELD_STATE_VIDEO,

	ORB_NES_FIELD_CPU_A,
	ORB_NES_FIELD_CPU_X,
	ORB_NES_FIELD_CPU_Y,
	ORB_NES_FIELD_CPU_S,
	ORB_NES_FIELD_CPU_P,
	ORB_NES_FIELD_CPU_PC,

	ORB_NES_FIELD_PPU_SPRITE_YPOS,
	ORB_NES_FIELD_PPU_SPRITE_XPOS,
	ORB_NES_FIELD_PPU_SPRITE_INDEX,
	ORB_NES_FIELD_PPU_SPRITE_ATTRS,

	ORB_NES_FIELD_PPU_XTICK,
	ORB_NES_FIELD_PPU_YTICK,
	ORB_NES_FIELD_PPU_T,
	ORB_NES_FIELD_PPU_V,
	ORB_NES_FIELD_PPU_X,
	ORB_NES_FIELD_PPU_W,
	ORB_NES_FIELD_PPU_TILE_ID,
	ORB_NES_FIELD_PPU_TILE_HI,
	ORB_NES_FIELD_PPU_TILE_LO,
	ORB_NES_FIELD_PPU_ATR_B,
	ORB_NES_FIELD_PPU_ATR_L0,
	ORB_NES_FIELD_PPU_ATR_L1,
	ORB_NES_FIELD_PPU_CHR_R0,
	ORB_NES_FIELD_PPU_CHR_R1,
	ORB_NES_FIELD_PPU_ATR_R0,
	ORB_NES_FIELD_PPU_ATR_R1,
	ORB_NES_FIELD_PPU_SPR0_ENABLE,
	ORB_NES_FIELD_PPU_SPR0_2CYCLE_DELAY,
	ORB_NES_FIELD_PPU_PPUCTRL,
	ORB_NES_FIELD_PPU_PPUMASK,
	ORB_NES_FIELD_PPU_PPUSTATUS,
	ORB_NES_FIELD_PPU_OAMADDR,
	ORB_NES_FIELD_PPU_DATA_READ_BUF,
	ORB_NES_FIELD_PPU_NSPRS,
	ORB_NES_FIELD_PPU_SPRS,
	ORB_NES_FIELD_PPU_OAM,
	ORB_NES_FIELD_PPU_PRAM,

	ORB_NES_FIELD_APU_DIVIDER_COUNTER,
	ORB_NES_FIELD_APU_DIVIDER_PERIOD,

	ORB_NES_FIELD_APU_SWEEP_DIVIDER,
	ORB_NES_FIELD_APU_SWEEP_RELOAD_DIVIDER,
	ORB_NES_FIELD_APU_SWEEP_SHIFT,
	ORB_NES_FIELD_APU_SWEEP_ENABLE,
	ORB_NES_FIELD_APU_SWEEP_NEGATE,

	ORB_NES_FIELD_APU_ENVELOPE_DIVIDER,
	ORB_NES_FIELD_APU_ENVELOPE_COUNTER,
	ORB_NES_FIELD_APU_ENVELOPE_RELOAD_DIVIDER,

	ORB_NES_FIELD_APU_PULSE_ENABLE,
	ORB_NES_FIELD_APU_PULSE_INFINITE_PLAY,
	ORB_NES_FIELD_APU_PULSE_LENGTH_COUNTER,
	ORB_NES_FIELD_APU_PULSE_VOLUME,
	ORB_NES_FIELD_APU_PULSE_USE_CONSTANT_VOLUME,
	ORB_NES_FIELD_APU_PULSE_SWEEP,
	ORB_NES_FIELD_APU_PULSE_ENVELOPE,
	ORB_NES_FIELD_APU_PULSE_DUTY_MASK,
	ORB_NES_FIELD_APU_PULSE_PHASE,
	ORB_NES_FIELD_APU_PULSE_TIMER,
	ORB_NES_FIELD_APU_PULSE_TIMER_PERIOD,

	ORB_NES_FIELD_APU_TRIANGLE_ENABLE,
	ORB_NES_FIELD_APU_TRIANGLE_LENGTH_COUNTER,
	ORB_NES_FIELD_APU_TRIANGLE_LENGTH_COUNTER_HALT,
	ORB_NES_FIELD_APU_TRIANGLE_LINEAR_COUNTER,
	ORB_NES_FIELD_APU_TRIANGLE_LINEAR_COUNTER_RELOAD,
	ORB_NES_FIELD_APU_TRIANGLE_LINEAR_COUNTER_RELOAD_VALUE,
	ORB_NES_FIELD_APU_TRIANGLE_WAVE_PHASE,
	ORB_NES_FIELD_APU_TRIANGLE_WAVE_PERIOD,
	ORB_NES_FIELD_APU_TRIANGLE_WAVE_TIMER,

	ORB_NES_FIELD_APU_IRQ_PENDING,
	ORB_NES_FIELD_APU_IRQ_INHIBIT,
	ORB_NES_FIELD_APU_RESET_DELAY,
	ORB_NES_FIELD_APU_RESET_MODE,
	ORB_NES_FIELD_APU_MODE,
	ORB_NES_FIELD_APU_STEP_INDEX,
	ORB_NES_FIELD_APU_CPU_CYCLE_COUNTER,
	ORB_NES_FIELD_APU_PULSE,
	ORB_NES_FIELD_APU_TRIANGLE,

	ORB_NES_FIELD_COUNT,
}
Orb_NESFieldId;

#define ORB_NES_FIELD(id_, type_, field_, wire_type_, record_id_, count_) \
	{ \
		.name = #field_, \
		.id = (id_), \
		.wire_type = (wire_type_), \
		.record_id = (record_id_), \
		.offset = offsetof(type_, field_), \
		.size = sizeof(((type_ *)0)->field_), \
		.count = (count_), \
		.flags = SERIALIZE_FIELD_ENABLED, \
	}

#define ORB_NES_SCALAR(id_, type_, field_, wire_type_, record_id_) \
	ORB_NES_FIELD(id_, type_, field_, wire_type_, record_id_, 1)

#define ORB_NES_ARRAY(id_, type_, field_, wire_type_, record_id_) \
	ORB_NES_FIELD(id_, type_, field_, wire_type_, record_id_, ArrayCount(((type_ *)0)->field_))

static const SerializeField orb_nes_cpu_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_CPU_A, NES_CPUState, A, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_CPU_X, NES_CPUState, X, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_CPU_Y, NES_CPUState, Y, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_CPU_S, NES_CPUState, S, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_CPU_P, NES_CPUState, P, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_CPU_PC, NES_CPUState, PC, SERIALIZE_WIRE_U16, 0),
};

static const SerializeField orb_nes_ppu_sprite_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_SPRITE_YPOS, NES_PPUSprite, ypos, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_SPRITE_XPOS, NES_PPUSprite, xpos, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_SPRITE_INDEX, NES_PPUSprite, index, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_SPRITE_ATTRS, NES_PPUSprite, attrs, SERIALIZE_WIRE_U8, 0),
};

static const SerializeField orb_nes_ppu_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_XTICK, NES_PPUState, xtick, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_YTICK, NES_PPUState, ytick, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_T, NES_PPUState, t, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_V, NES_PPUState, v, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_X, NES_PPUState, x, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_W, NES_PPUState, w, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_TILE_ID, NES_PPUState, tile_id, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_TILE_HI, NES_PPUState, tile_hi, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_TILE_LO, NES_PPUState, tile_lo, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_ATR_B, NES_PPUState, atr_b, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_ATR_L0, NES_PPUState, atr_l0, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_ATR_L1, NES_PPUState, atr_l1, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_CHR_R0, NES_PPUState, chr_r0, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_CHR_R1, NES_PPUState, chr_r1, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_ATR_R0, NES_PPUState, atr_r0, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_ATR_R1, NES_PPUState, atr_r1, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_SPR0_ENABLE, NES_PPUState, spr0_enable, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_SPR0_2CYCLE_DELAY, NES_PPUState, spr0_2cycle_delay, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_PPUCTRL, NES_PPUState, PPUCTRL, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_PPUMASK, NES_PPUState, PPUMASK, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_PPUSTATUS, NES_PPUState, PPUSTATUS, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_OAMADDR, NES_PPUState, OAMADDR, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_DATA_READ_BUF, NES_PPUState, data_read_buf, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_PPU_NSPRS, NES_PPUState, nsprs, SERIALIZE_WIRE_U8, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_PPU_SPRS, NES_PPUState, sprs, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_PPU_SPRITE),
	ORB_NES_ARRAY(ORB_NES_FIELD_PPU_OAM, NES_PPUState, OAM, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_PPU_SPRITE),
	ORB_NES_ARRAY(ORB_NES_FIELD_PPU_PRAM, NES_PPUState, _pram, SERIALIZE_WIRE_U8, 0),
};

static const SerializeField orb_nes_apu_divider_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_DIVIDER_COUNTER, NES_APUDivider, counter, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_DIVIDER_PERIOD, NES_APUDivider, period, SERIALIZE_WIRE_U8, 0),
};

static const SerializeField orb_nes_apu_sweep_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_SWEEP_DIVIDER, NES_APUSweep, divider, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU_DIVIDER),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_SWEEP_RELOAD_DIVIDER, NES_APUSweep, reload_divider, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_SWEEP_SHIFT, NES_APUSweep, shift, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_SWEEP_ENABLE, NES_APUSweep, enable, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_SWEEP_NEGATE, NES_APUSweep, negate, SERIALIZE_WIRE_U8, 0),
};

static const SerializeField orb_nes_apu_envelope_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_ENVELOPE_DIVIDER, NES_APUEnvelope, divider, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU_DIVIDER),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_ENVELOPE_COUNTER, NES_APUEnvelope, counter, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_ENVELOPE_RELOAD_DIVIDER, NES_APUEnvelope, reload_divider, SERIALIZE_WIRE_U8, 0),
};

static const SerializeField orb_nes_apu_pulse_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_ENABLE, NES_APU_Pulse, enable, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_INFINITE_PLAY, NES_APU_Pulse, infinite_play, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_LENGTH_COUNTER, NES_APU_Pulse, length_counter, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_VOLUME, NES_APU_Pulse, volume, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_USE_CONSTANT_VOLUME, NES_APU_Pulse, use_constant_volume, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_SWEEP, NES_APU_Pulse, sweep, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU_SWEEP),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_ENVELOPE, NES_APU_Pulse, env, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU_ENVELOPE),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_DUTY_MASK, NES_APU_Pulse, duty_mask, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_PHASE, NES_APU_Pulse, phase, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_TIMER, NES_APU_Pulse, timer, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_PULSE_TIMER_PERIOD, NES_APU_Pulse, timer_period, SERIALIZE_WIRE_U16, 0),
};

static const SerializeField orb_nes_apu_triangle_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_ENABLE, NES_APU_Triangle, enable, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_LENGTH_COUNTER, NES_APU_Triangle, length_counter, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_LENGTH_COUNTER_HALT, NES_APU_Triangle, length_counter_halt, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_LINEAR_COUNTER, NES_APU_Triangle, linear_counter, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_LINEAR_COUNTER_RELOAD, NES_APU_Triangle, linear_counter_reload, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_LINEAR_COUNTER_RELOAD_VALUE, NES_APU_Triangle, linear_counter_reload_value, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_WAVE_PHASE, NES_APU_Triangle, wave_phase, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_WAVE_PERIOD, NES_APU_Triangle, wave_period, SERIALIZE_WIRE_U16, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE_WAVE_TIMER, NES_APU_Triangle, wave_timer, SERIALIZE_WIRE_U16, 0),
};

static const SerializeField orb_nes_apu_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_IRQ_PENDING, NES_APUState, irq_pending, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_IRQ_INHIBIT, NES_APUState, irq_inhibit, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_RESET_DELAY, NES_APUState, reset_delay, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_RESET_MODE, NES_APUState, reset_mode, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_MODE, NES_APUState, mode, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_STEP_INDEX, NES_APUState, step_index, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_CPU_CYCLE_COUNTER, NES_APUState, cpu_cycle_counter, SERIALIZE_WIRE_U16, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_APU_PULSE, NES_APUState, pulse, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU_PULSE),
	ORB_NES_SCALAR(ORB_NES_FIELD_APU_TRIANGLE, NES_APUState, triangle, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU_TRIANGLE),
};

static const SerializeField orb_nes_state_fields[] =
{
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_SCHEDULER_CLOCK, NES_Emulator, scheduler_clock, SERIALIZE_WIRE_U64, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_SAMPLE_PHASE, NES_Emulator, sample_phase, SERIALIZE_WIRE_U64, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_VALUES, NES_Emulator, values, SERIALIZE_WIRE_U8, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_INPUT, NES_Emulator, input_state, SERIALIZE_WIRE_BYTES, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_CPU_STALL_CYCLES, NES_Emulator, cpu_stall_cycles, SERIALIZE_WIRE_U32, 0),
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_CPU, NES_Emulator, cpu, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_CPU),
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_PPU, NES_Emulator, ppu, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_PPU),
	ORB_NES_SCALAR(ORB_NES_FIELD_STATE_APU, NES_Emulator, apu, SERIALIZE_WIRE_RECORD, ORB_NES_RECORD_APU),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_CONTROLLERS, NES_Emulator, controllers, SERIALIZE_WIRE_U8, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_WRAM, NES_Emulator, _wram, SERIALIZE_WIRE_U8, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_VRAM, NES_Emulator, _vram, SERIALIZE_WIRE_U8, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_CHR_RAM, NES_Emulator, chr_ram, SERIALIZE_WIRE_U8, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_PRG_RAM, NES_Emulator, prg_ram, SERIALIZE_WIRE_U8, 0),
	ORB_NES_ARRAY(ORB_NES_FIELD_STATE_VIDEO, NES_Emulator, video, SERIALIZE_WIRE_U8, 0),
};

#define ORB_NES_RECORD(id_, type_, fields_) \
	[id_] = { \
		.name = #type_, \
		.id = (id_), \
		.size = sizeof(type_), \
		.fields = (fields_), \
		.field_count = ArrayCount(fields_), \
	}

static const SerializeRecord orb_nes_records[ORB_NES_RECORD_COUNT] =
{
	ORB_NES_RECORD(ORB_NES_RECORD_STATE, NES_Emulator, orb_nes_state_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_CPU, NES_CPUState, orb_nes_cpu_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_PPU, NES_PPUState, orb_nes_ppu_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_PPU_SPRITE, NES_PPUSprite, orb_nes_ppu_sprite_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_APU, NES_APUState, orb_nes_apu_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_APU_DIVIDER, NES_APUDivider, orb_nes_apu_divider_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_APU_SWEEP, NES_APUSweep, orb_nes_apu_sweep_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_APU_ENVELOPE, NES_APUEnvelope, orb_nes_apu_envelope_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_APU_PULSE, NES_APU_Pulse, orb_nes_apu_pulse_fields),
	ORB_NES_RECORD(ORB_NES_RECORD_APU_TRIANGLE, NES_APU_Triangle, orb_nes_apu_triangle_fields),
};

static const SerializeRecordMap orb_nes_record_map =
{
	.records = orb_nes_records,
	.record_count = ArrayCount(orb_nes_records),
};

ByteSpan orb_nes_state_encode(Arena *arena, const NES_Emulator *emulator)
{
	if (!arena || !arena->memory || !emulator) return (ByteSpan) {};
	if (!nes_emulator_has_cartridge(emulator)) return (ByteSpan) {};
	if (arena->position > arena->reserved_size || ORB_NES_STATE_MAX_ENCODED_SIZE > arena->reserved_size - arena->position) return (ByteSpan) {};
	u8 *start = arena_top(arena);
	arena_ensure_committed(arena, ORB_NES_STATE_MAX_ENCODED_SIZE);
	u64 size = serialize_write_record(byte_span(start, ORB_NES_STATE_MAX_ENCODED_SIZE), &orb_nes_record_map, ORB_NES_RECORD_STATE, emulator);
	Assert(size <= ORB_NES_STATE_MAX_ENCODED_SIZE);
	arena->position += size;
	return byte_span(start, size);
}

b32 orb_nes_state_decode(NES_Emulator *emulator, ByteSpan state)
{
	if (!emulator || !nes_emulator_has_cartridge(emulator)) return false;
	NES_Emulator *decoded = calloc(1, sizeof(*decoded));
	if (!decoded) return false;
	b32 success = serialize_read_record(state, &orb_nes_record_map, ORB_NES_RECORD_STATE, decoded);
	if (success) success = nes_emulator_valid(decoded);
	if (success)
	{
		for (u32 index = 0; index < ArrayCount(orb_nes_state_fields); ++index)
		{
			const SerializeField *field = &orb_nes_state_fields[index];
			memory_copy((u8 *)emulator + field->offset, (u8 *)decoded + field->offset, field->size);
		}
		emulator->cpu_bus_metrics = (NES_BusMetrics) {};
		emulator->ppu_bus_metrics = (NES_BusMetrics) {};
		emulator->scheduler_trace_index = 0;
		memory_zero(emulator->scheduler_trace, sizeof(emulator->scheduler_trace));
	}
	free(decoded);
	return success;
}
