
// NOTE(RJ) eventually these could become scripts
typedef enum
{
	APP_ACTION_NONE,
	APP_ACTION_TOGGLE_LIBRARY_OVERLAY,
	APP_ACTION_SPLIT_PANEL_HORIZONTALLY,
	APP_ACTION_SPLIT_PANEL_VERTICALLY,
	APP_ACTION_CLOSE_PANEL,
	APP_ACTION_OPEN_VIEW_0,
	APP_ACTION_OPEN_VIEW_1,
	APP_ACTION_OPEN_VIEW_2,
	APP_ACTION_OPEN_VIEW_3,
	APP_ACTION_OPEN_VIEW_4,
	APP_ACTION_OPEN_VIEW_5,
	APP_ACTION_OPEN_VIEW_6,
	APP_ACTION_OPEN_VIEW_7,
	APP_ACTION_OPEN_VIEW_8,
	APP_ACTION_OPEN_VIEW_9,
	APP_ACTION_OPEN_VIEW_10,
	APP_ACTION_OPEN_VIEW_11,
	APP_ACTION_OPEN_VIEW_12,
	APP_ACTION_OPEN_VIEW_13,
	APP_ACTION_OPEN_VIEW_14,
	APP_ACTION_OPEN_VIEW_15,

	APP_ACTION_BEGIN_REWINDING_BACKWARDS,
	APP_ACTION_BEGIN_REWINDING_FORWARD,
	APP_ACTION_STOP_REWINDING,

	APP_ACTION_SUPPRESS_EMULATOR_INPUT,
	APP_ACTION_TOGGLE_FULLSCREEN,
	APP_ACTION_TOGGLE_PPU_FULLSCREEN,
	APP_ACTION_EXIT_PPU_FULLSCREEN,
	APP_ACTION_OPEN_ROM,
	APP_ACTION_RESET,
	APP_ACTION_SAVE_STATE,
	APP_ACTION_RESTORE_STATE,
	APP_ACTION_DUMP_PROGRAM,
	APP_ACTION_TOGGLE_RUNNING,
	APP_ACTION_STEP,
	APP_ACTION_TOGGLE_PPU_CAPTURE,
	APP_ACTION_TOGGLE_APP_CAPTURE,
	APP_ACTION_TOGGLE_CRT,
	APP_ACTION_INCREASE_UI_FONT_SIZE,
	APP_ACTION_DECREASE_UI_FONT_SIZE,
	APP_ACTION_RESET_UI_FONT_SIZE,
	APP_ACTION_MUTE,
	APP_LOWER_VOLUME,
	APP_RAISE_VOLUME,
}
AppAction;

typedef enum
{
	KEY_CHORD_ON_RELEASE = OS_EVENT_KEY_RELEASE,
	KEY_CHORD_ON_PRESSED = OS_EVENT_KEY_PRESS,
}
KeyChordActivation;

typedef struct {
	KeyChordActivation activation;
	OS_Key             key;
	OS_ModifierFlags   modifiers;
}
KeyChord;

typedef struct {
	AppAction action;
	KeyChord  key_chord;
}
KeyBind;